- name: configure nginx
  include: nginx.yml
  tags:
   - frontend
   - frontend_nginx

- name: set up certsync from front
  include: certsync.yml
  tags:
   - frontend
   - frontend_certsync

- name: configure dehydrated
  include: dehydrated.yml
  tags:
   - frontend
   - frontend_dehydrated

- name: deploy nginx conf.d/ssl.conf
  template:
    src: nginx-conf.d-ssl.conf.j2
    dest: /etc/nginx/conf.d/ssl.conf
  notify:
   - reload nginx
  tags:
   - frontend
   - frontend_dehydrated
   - frontend_nginx

- name: deploy nginx conf.d/dl-ssl.conf
  template:
    src: nginx-conf.d-dl-ssl.conf.j2
    dest: /etc/nginx/conf.d/dl-ssl.conf
  notify:
   - reload nginx
  tags:
   - frontend
   - frontend_certsync
   - frontend_nginx

- name: deploy nginx conf.d/webroot-ssl.conf
  template:
    src: nginx-conf.d-webroot-ssl.conf.j2
    dest: /etc/nginx/conf.d/webroot-ssl.conf
  notify:
   - reload nginx
  tags:
   - frontend
   - frontend_certsync
   - frontend_nginx
