# tasks just for "native" (admin exclusively by flathub.org) hosts

- name: ensure hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: disable ssh password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: reload sshd

- name: enable fail2ban service
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: configure postfix
  template:
    src: postfix-main.cf.j2
    dest: /etc/postfix/main.cf
  when: base_postfix_relayhost is defined
  notify:
   - reload postfix

- name: install aliases file
  copy:
    src: aliases
    dest: /etc/aliases
  notify:
   - trigger newaliases

- name: install fail2ban jail.local
  copy:
    src: fail2ban-jail.local
    dest: /etc/fail2ban/jail.local
  notify:
   - reload fail2ban
