# TODO: Split all deb and rpm intallations into their own roles
- name: install epel-release
  yum:
    name: epel-release
    state: present
  when: ansible_distribution == "CentOS"
  tags:
   - base
   - update

- name: add git-maint COPR
  copy:
    src: group_git-maint-git-epel-7.repo
    dest: /etc/yum.repos.d/group_git-maint-git-epel-7.repo
  when: ansible_distribution == "CentOS"
  tags:
   - base
   - update

- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  tags:
   - base
   - update

- name: install base packages
  package:
    name: "{{ base_packages + base_packages_rpm }}"
  tags:
   - base
